---
- name: Create new bridge
  become: true
  ignore_errors: true
  docker_network:
    name: defaultnet
    driver_options:
      com.docker.network.bridge.name: dockerbridge0
    ipam_options:
      subnet: '192.168.13.0/24'
      gateway: 192.168.13.1

- name: Start portainer
  become: true
  docker_container:
    name: portainer
    hostname: portainer
    image: portainer/portainer
    restart_policy: unless-stopped
    recreate: true
    purge_networks: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/portainer:/data
    ports:
      - 127.0.0.1:9000:9000
    networks:
    - name: defaultnet

- name: copy mailserver config
  become: true
  copy:
    src: "templates/opt/docker/mailserver.env"
    dest: "/opt/docker/mailserver.env"

- name: Start Mailserver
  become: true
  docker_container:
    name: mail
    hostname: auskunftsbegehren.at
    image: tvial/docker-mailserver:latest
    restart_policy: unless-stopped
    recreate: true
    purge_networks: true
    env_file: /opt/docker/mailserver.env
    volumes:
      - /opt/docker/mail/mail:/var/mail
      - /opt/docker/mail/state:/var/mail-state
      - /opt/docker/mail/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    capabilities:
      - NET_ADMIN
    networks:
    - name: defaultnet

- name: Start webmail
  become: true
  docker_container:
    name: webmail
    hostname: webmail
    image: hardware/rainloop
    restart_policy: unless-stopped
    recreate: true
    purge_networks: true
    volumes:
      - /opt/docker/mail/webmail:/rainloop/data
    ports:
      - "127.0.0.1:8888:8888"
    networks:
    - name: defaultnet
