---
- name: Install Nginx
  become: true
  apt:
    name: nginx
    state: present

- name: OCSP Response Folder
  become: true
  file:
    path: /etc/nginx/vhosts.d
    state: directory

- name: Copy nginx config
  become: true
  template:
    src: templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy nginx additional config
  become: true
  template:
    src: "templates/etc/nginx/conf.d/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
  with_items:
    - folder
    - tls
    - proxy
  notify:
    - restart nginx

- name: Copy nginx vhost config
  become: true
  template:
    src: "templates/etc/nginx/vhosts.d/{{ item }}.conf"
    dest: "/etc/nginx/vhosts.d/{{ item }}.conf"
  with_items:
    - goatberger.cyber-perikarp.eu
    - auskunftsbegehren.at
    - mail.auskunftsbegehren.at
    - dev.auskunftsbegehren.at

  notify:
    - restart nginx

- name: Start and enable nginx
  become: true
  service:
    name: nginx
    state: started
    enabled: true
