---
- name: Install Basics
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - gnupg-agent
    - htop
    - qemu-guest-agent
    - ccze

- name: apt-get autoremove
  become: true
  apt:
    autoremove: yes
    autoclean: yes
