---
- name: Apt Keys from Keyserver
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ item }}"
    state: present
  with_items:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 # Docker
    - ABF5BD827BD9BF62 # Nginx

- name: apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Apt sources.list
  become: true
  copy:
    src: templates/etc/apt/sources.list
    dest: /etc/apt/sources.list

- name: Enable Repos
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - 'ppa:certbot/certbot'
    - 'deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx'
    - 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
