---
- name: SSHD config
  become: true
  copy:
    src: templates/etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config

- name: Remove packaged certbot Cronjob
  become: true
  file:
    path: /etc/cron.d/certbot
    state: absent

- name: DH Folder
  become: true
  file:
    path: /etc/ssl/dh
    state: directory

- name: OSCP Response Folder
  become: true
  file:
    path: /etc/ssl/oscp
    state: directory

- name: Install security tools
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - fail2ban
    - iptables
    - certbot

- name: Copy fail2ban config
  become: true
  template:
    src: templates/etc/fail2ban/fail2ban.d/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.d/fail2ban.conf
  notify:
    - restart fail2ban

- name: Copy fail2ban jail config
  become: true
  template:
    src: templates/etc/fail2ban/jail.d/jail.conf
    dest: /etc/fail2ban/jail.d/jail.conf
  notify:
    - restart fail2ban
